"""product removing bugs Migration

Revision ID: 88940868ba75
Revises: 9f938277bda3
Create Date: 2019-09-24 18:56:56.198587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88940868ba75'
down_revision = '9f938277bda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photoprofiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('pitches', 'contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('contents', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'content')
    op.drop_table('photoprofiles')
    # ### end Alembic commands ###
